AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 120
Documentation:
  Enabled: false
Style/BlockComments:
  Enabled: false
