# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc9f0c4e2051f364ba091d85ca1d377ee7497ed70ea6058b2119b48ae074e611e72769858bc2dfa367a8a981376c42f8996fac3e786b92d11843b45917b93cce

test:
  secret_key_base: 765bbe762c2f77dd4c386663fb5560e8610f9d163e431eff5c14f35ea820fe8a11b21c8b098e910e196a671a6393e14d687ad6c5ffbbd9a3cb7760e990af17d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
